title: Wax Documentation +
description: An extended supplement to the Wax documentation produced by Minicomp
theme: just-the-docs

url: https://https://kam535.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
